name: Everest Trading Bot

on:
  schedule:
    # सकाळी ०३:०० UTC म्हणजे भारताचे सकाळी ८:३०
    - cron: '0 3 * * *'
    # दुपारी ०३:४५ UTC म्हणजे मार्केट क्लोज समरीसाठी (१०:१५ UTC)
    - cron: '15 10 * * *'
  workflow_dispatch: # मॅन्युअली रन करण्यासाठी बटण मिळेल

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USER_ID: ${{ secrets.USER_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOTP_TOKEN: ${{ secrets.TOTP_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main_bot.py
